# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
    name: Default

steps:
  - checkout: self
  - task: NodeTool@0
    displayName: Use Node 12.18.2
    inputs:
      versionSpec: 12.18.2
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: $(System.DefaultWorkingDirectory)
      verbose: false
  - task: PowerShell@2
    displayName: ng build
    inputs:
      targetType: inline
      script: >
        .\node_modules\.bin\ng build
      workingDirectory: $(System.DefaultWorkingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Artifacts'
    inputs:
      PathtoPublish: $(System.DefaultWorkingDirectory)\dist
      ArtifactName: Artifacts