apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment  
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: fpintopi/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP    
    targetPort: 80
  type: LoadBalancer
   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    kkubernetes.io/ingress.class: nginx  
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1 
spec:
  rules:
  - http:
      paths:      
      - backend:
          serviceName: frontend-service
          servicePort: 80
        path: /?(.*)

